- name: ensure zookeeper is running (and enable it at boot)
  sudo: yes
  service:
    name: zookeeper
    state: started
    enabled: yes
  tags:
    - zookeeper

- name: Create zookeeper config file
  template:
    src: zoo.cfg.j2
    dest: /etc/zookeeper/conf/zoo.cfg
  sudo: yes
  notify:
    - restart zookeeper
  tags:
    - zookeeper

- name: Create zookeeper logging config
  template:
    src: log4j.properties.j2
    dest: /etc/zookeeper/conf/log4j.properties
  sudo: yes
  notify:
    - restart zookeeper
  tags:
    - zookeeper

- name: Enable syslog for zookeeper
  sudo: yes
  lineinfile:
    dest: /etc/zookeeper/conf/environment
    state: present
    regexp: ^ZOO_LOG4J_PROP=
    line: 'ZOO_LOG4J_PROP=\"INFO,LOGSTASH,ROLLINGFILE\"'
  notify:
    - restart docker

- name: Create zookeeper myid file
  copy:
    content: "{{ zookeeper_id }}"
    dest: /etc/zookeeper/conf/myid
    mode: 0644
  sudo: yes
  notify:
    - restart zookeeper
  tags:
    - zookeeper

- name: Set Zookeeper consul service definition
  sudo: yes
  template:
    src: zookeeper-consul.j2
    dest: "{{ consul_dir }}/zookeeper.json"
  notify:
    - restart consul
  tags:
    - zookeeper
