---
# Install (docker-py) python package as is a docker module dependency.
- pip: name=docker-py version=1.1.0

# tasks for running logspout
- name: run logspout container
  when: logspout_enabled
  docker:
    name: logspout
    image: "{{ logspout_image }}"
    state: started
    restart_policy: "{{ logspout_restart_policy }}"
    net: "{{ logspout_net }}"
    ports:
      - "{{ logspout_host_port }}:80"
    command: "syslog://{{ logspout_hostname }}:5000"
    hostname: "{{ logspout_hostname }}"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  tags:
    - logstash

- name: upload logspout template service
  when: logspout_enabled
  template:
    src: logspout.conf.j2
    dest: /etc/init/logspout.conf
    mode: 0755
  sudo: yes
  tags:
    - logstash

- name: create configuration directory
  sudo: yes
  file:
    path: /etc/logstash.d
    state: directory
    mode: 0755
  tags:
    - logstash

- name: configure logstash
  sudo: yes
  template:
    src: logstash.conf.j2
    dest: /etc/logstash.d/logstash.conf
  tags:
    - logstash

# Attach to the running container, or start it if needed
# and forward all signals so that the process manager can detect
# when a container stops and correctly restart it.
- name: ensure logspout is running (and enable it at boot)
  when: logspout_enabled
  sudo: yes
  service:
    name: logspout
    state: started
    enabled: yes
  tags:
    - logstash

- name: Set logspout consul service definition
  sudo: yes
  template:
    src: logspout-consul.j2
    dest: "{{ logspout_consul_dir }}/logspout.json"
  notify:
    - restart consul
  when: logspout_enabled

- name: ensure logspout is running (and enable it at boot)
  when: not logspout_enabled
  sudo: yes
  service:
    name: logspout
    state: stopped
    enabled: yes
  tags:
    - logstash
